// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: PB/content.proto

package content_pb

import (
	common_pb "go_projects/praProject1/PB/pb/common_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 帖子类型
type PostType int32

const (
	PostType_POST_TYPE_UNSPECIFIED PostType = 0
	PostType_POST_TYPE_GENERAL     PostType = 1 // 通用帖子
	PostType_POST_TYPE_LOST_FOUND  PostType = 2 // 失物招领
	PostType_POST_TYPE_SECOND_HAND PostType = 3 // 二手交易
)

// Enum value maps for PostType.
var (
	PostType_name = map[int32]string{
		0: "POST_TYPE_UNSPECIFIED",
		1: "POST_TYPE_GENERAL",
		2: "POST_TYPE_LOST_FOUND",
		3: "POST_TYPE_SECOND_HAND",
	}
	PostType_value = map[string]int32{
		"POST_TYPE_UNSPECIFIED": 0,
		"POST_TYPE_GENERAL":     1,
		"POST_TYPE_LOST_FOUND":  2,
		"POST_TYPE_SECOND_HAND": 3,
	}
)

func (x PostType) Enum() *PostType {
	p := new(PostType)
	*p = x
	return p
}

func (x PostType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostType) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_content_proto_enumTypes[0].Descriptor()
}

func (PostType) Type() protoreflect.EnumType {
	return &file_PB_content_proto_enumTypes[0]
}

func (x PostType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostType.Descriptor instead.
func (PostType) EnumDescriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{0}
}

// 帖子状态
type PostStatus int32

const (
	PostStatus_POST_STATUS_UNSPECIFIED PostStatus = 0
	PostStatus_POST_STATUS_PENDING     PostStatus = 1 // 审核中
	PostStatus_POST_STATUS_PUBLISHED   PostStatus = 2 // 已发布
	PostStatus_POST_STATUS_EXPIRED     PostStatus = 3 // 已过期
	PostStatus_POST_STATUS_CLOSED      PostStatus = 4 // 已关闭
	PostStatus_POST_STATUS_REJECTED    PostStatus = 5 // 已拒绝
	PostStatus_POST_STATUS_RETRIEVED   PostStatus = 6 // 失物已当领（失物招领专用）
	PostStatus_POST_STATUS_SOLD        PostStatus = 7 // 二手已售出（二手交易专用）
)

// Enum value maps for PostStatus.
var (
	PostStatus_name = map[int32]string{
		0: "POST_STATUS_UNSPECIFIED",
		1: "POST_STATUS_PENDING",
		2: "POST_STATUS_PUBLISHED",
		3: "POST_STATUS_EXPIRED",
		4: "POST_STATUS_CLOSED",
		5: "POST_STATUS_REJECTED",
		6: "POST_STATUS_RETRIEVED",
		7: "POST_STATUS_SOLD",
	}
	PostStatus_value = map[string]int32{
		"POST_STATUS_UNSPECIFIED": 0,
		"POST_STATUS_PENDING":     1,
		"POST_STATUS_PUBLISHED":   2,
		"POST_STATUS_EXPIRED":     3,
		"POST_STATUS_CLOSED":      4,
		"POST_STATUS_REJECTED":    5,
		"POST_STATUS_RETRIEVED":   6,
		"POST_STATUS_SOLD":        7,
	}
)

func (x PostStatus) Enum() *PostStatus {
	p := new(PostStatus)
	*p = x
	return p
}

func (x PostStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_content_proto_enumTypes[1].Descriptor()
}

func (PostStatus) Type() protoreflect.EnumType {
	return &file_PB_content_proto_enumTypes[1]
}

func (x PostStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostStatus.Descriptor instead.
func (PostStatus) EnumDescriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{1}
}

// 物品分类（失物招领 & 二手交易共用）
type ItemCategory int32

const (
	ItemCategory_ITEM_CATEGORY_UNSPECIFIED ItemCategory = 0
	ItemCategory_ITEM_CATEGORY_DIGITAL     ItemCategory = 1 // 手机/数码
	ItemCategory_ITEM_CATEGORY_CERTIFICATE ItemCategory = 2 // 证件/卡类
	ItemCategory_ITEM_CATEGORY_KEY         ItemCategory = 3 // 钥匙/门卡
	ItemCategory_ITEM_CATEGORY_BOOK        ItemCategory = 4 // 书籍/资料
	ItemCategory_ITEM_CATEGORY_CLOTHING    ItemCategory = 5 // 服装/饰品
	ItemCategory_ITEM_CATEGORY_CHARGER     ItemCategory = 6 // 充电器/配件
	ItemCategory_ITEM_CATEGORY_DAILY       ItemCategory = 7 // 生活用品
	ItemCategory_ITEM_CATEGORY_OTHER       ItemCategory = 8 // 其他
)

// Enum value maps for ItemCategory.
var (
	ItemCategory_name = map[int32]string{
		0: "ITEM_CATEGORY_UNSPECIFIED",
		1: "ITEM_CATEGORY_DIGITAL",
		2: "ITEM_CATEGORY_CERTIFICATE",
		3: "ITEM_CATEGORY_KEY",
		4: "ITEM_CATEGORY_BOOK",
		5: "ITEM_CATEGORY_CLOTHING",
		6: "ITEM_CATEGORY_CHARGER",
		7: "ITEM_CATEGORY_DAILY",
		8: "ITEM_CATEGORY_OTHER",
	}
	ItemCategory_value = map[string]int32{
		"ITEM_CATEGORY_UNSPECIFIED": 0,
		"ITEM_CATEGORY_DIGITAL":     1,
		"ITEM_CATEGORY_CERTIFICATE": 2,
		"ITEM_CATEGORY_KEY":         3,
		"ITEM_CATEGORY_BOOK":        4,
		"ITEM_CATEGORY_CLOTHING":    5,
		"ITEM_CATEGORY_CHARGER":     6,
		"ITEM_CATEGORY_DAILY":       7,
		"ITEM_CATEGORY_OTHER":       8,
	}
)

func (x ItemCategory) Enum() *ItemCategory {
	p := new(ItemCategory)
	*p = x
	return p
}

func (x ItemCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_content_proto_enumTypes[2].Descriptor()
}

func (ItemCategory) Type() protoreflect.EnumType {
	return &file_PB_content_proto_enumTypes[2]
}

func (x ItemCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemCategory.Descriptor instead.
func (ItemCategory) EnumDescriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{2}
}

// 成色（二手交易专用）
type Condition int32

const (
	Condition_CONDITION_UNSPECIFIED Condition = 0
	Condition_CONDITION_BRAND_NEW   Condition = 1 // 全新
	Condition_CONDITION_LIKE_NEW    Condition = 2 // 几乎全新
	Condition_CONDITION_GOOD        Condition = 3 // 良好
	Condition_CONDITION_FAIR        Condition = 4 // 一般
)

// Enum value maps for Condition.
var (
	Condition_name = map[int32]string{
		0: "CONDITION_UNSPECIFIED",
		1: "CONDITION_BRAND_NEW",
		2: "CONDITION_LIKE_NEW",
		3: "CONDITION_GOOD",
		4: "CONDITION_FAIR",
	}
	Condition_value = map[string]int32{
		"CONDITION_UNSPECIFIED": 0,
		"CONDITION_BRAND_NEW":   1,
		"CONDITION_LIKE_NEW":    2,
		"CONDITION_GOOD":        3,
		"CONDITION_FAIR":        4,
	}
)

func (x Condition) Enum() *Condition {
	p := new(Condition)
	*p = x
	return p
}

func (x Condition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Condition) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_content_proto_enumTypes[3].Descriptor()
}

func (Condition) Type() protoreflect.EnumType {
	return &file_PB_content_proto_enumTypes[3]
}

func (x Condition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Condition.Descriptor instead.
func (Condition) EnumDescriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{3}
}

// 交易方式（二手交易专用）
type TradeMethod int32

const (
	TradeMethod_TRADE_METHOD_UNSPECIFIED  TradeMethod = 0
	TradeMethod_TRADE_METHOD_FACE_TO_FACE TradeMethod = 1 // 面交
	TradeMethod_TRADE_METHOD_DELIVERY     TradeMethod = 2 // 快递
)

// Enum value maps for TradeMethod.
var (
	TradeMethod_name = map[int32]string{
		0: "TRADE_METHOD_UNSPECIFIED",
		1: "TRADE_METHOD_FACE_TO_FACE",
		2: "TRADE_METHOD_DELIVERY",
	}
	TradeMethod_value = map[string]int32{
		"TRADE_METHOD_UNSPECIFIED":  0,
		"TRADE_METHOD_FACE_TO_FACE": 1,
		"TRADE_METHOD_DELIVERY":     2,
	}
)

func (x TradeMethod) Enum() *TradeMethod {
	p := new(TradeMethod)
	*p = x
	return p
}

func (x TradeMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_content_proto_enumTypes[4].Descriptor()
}

func (TradeMethod) Type() protoreflect.EnumType {
	return &file_PB_content_proto_enumTypes[4]
}

func (x TradeMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeMethod.Descriptor instead.
func (TradeMethod) EnumDescriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{4}
}

// 丢失/拾取标识（失物招领专用）
type LostOrFoundType int32

const (
	LostOrFoundType_LOST_OR_FOUND_UNSPECIFIED LostOrFoundType = 0
	LostOrFoundType_LOST_OR_FOUND_LOST        LostOrFoundType = 1 // 我丢失了
	LostOrFoundType_LOST_OR_FOUND_FOUND       LostOrFoundType = 2 // 我拾到了
)

// Enum value maps for LostOrFoundType.
var (
	LostOrFoundType_name = map[int32]string{
		0: "LOST_OR_FOUND_UNSPECIFIED",
		1: "LOST_OR_FOUND_LOST",
		2: "LOST_OR_FOUND_FOUND",
	}
	LostOrFoundType_value = map[string]int32{
		"LOST_OR_FOUND_UNSPECIFIED": 0,
		"LOST_OR_FOUND_LOST":        1,
		"LOST_OR_FOUND_FOUND":       2,
	}
)

func (x LostOrFoundType) Enum() *LostOrFoundType {
	p := new(LostOrFoundType)
	*p = x
	return p
}

func (x LostOrFoundType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LostOrFoundType) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_content_proto_enumTypes[5].Descriptor()
}

func (LostOrFoundType) Type() protoreflect.EnumType {
	return &file_PB_content_proto_enumTypes[5]
}

func (x LostOrFoundType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LostOrFoundType.Descriptor instead.
func (LostOrFoundType) EnumDescriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{5}
}

// 评论状态
type CommentStatus int32

const (
	CommentStatus_COMMENT_STATUS_UNSPECIFIED CommentStatus = 0
	CommentStatus_COMMENT_STATUS_NORMAL      CommentStatus = 1 // 正常
	CommentStatus_COMMENT_STATUS_DELETED     CommentStatus = 2 // 已删除（软删除）
)

// Enum value maps for CommentStatus.
var (
	CommentStatus_name = map[int32]string{
		0: "COMMENT_STATUS_UNSPECIFIED",
		1: "COMMENT_STATUS_NORMAL",
		2: "COMMENT_STATUS_DELETED",
	}
	CommentStatus_value = map[string]int32{
		"COMMENT_STATUS_UNSPECIFIED": 0,
		"COMMENT_STATUS_NORMAL":      1,
		"COMMENT_STATUS_DELETED":     2,
	}
)

func (x CommentStatus) Enum() *CommentStatus {
	p := new(CommentStatus)
	*p = x
	return p
}

func (x CommentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_content_proto_enumTypes[6].Descriptor()
}

func (CommentStatus) Type() protoreflect.EnumType {
	return &file_PB_content_proto_enumTypes[6]
}

func (x CommentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentStatus.Descriptor instead.
func (CommentStatus) EnumDescriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{6}
}

// 失物招领扩展字段
type LostFoundExtra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`                                                     // 丢失/拾取地点（文字描述）
	ItemCategory  ItemCategory           `protobuf:"varint,2,opt,name=item_category,json=itemCategory,proto3,enum=pb.ItemCategory" json:"item_category,omitempty"`   // 物品分类
	Contact       string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`                                                       // 联系方式（手机/微信，禁止索引到 ES）
	LostOrFound   LostOrFoundType        `protobuf:"varint,4,opt,name=lost_or_found,json=lostOrFound,proto3,enum=pb.LostOrFoundType" json:"lost_or_found,omitempty"` // 丢失/拾取标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LostFoundExtra) Reset() {
	*x = LostFoundExtra{}
	mi := &file_PB_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LostFoundExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LostFoundExtra) ProtoMessage() {}

func (x *LostFoundExtra) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LostFoundExtra.ProtoReflect.Descriptor instead.
func (*LostFoundExtra) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{0}
}

func (x *LostFoundExtra) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LostFoundExtra) GetItemCategory() ItemCategory {
	if x != nil {
		return x.ItemCategory
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *LostFoundExtra) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *LostFoundExtra) GetLostOrFound() LostOrFoundType {
	if x != nil {
		return x.LostOrFound
	}
	return LostOrFoundType_LOST_OR_FOUND_UNSPECIFIED
}

// 二手交易扩展字段
type SecondHandExtra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`                                                       // 期望售价（元）
	OriginalPrice float64                `protobuf:"fixed64,2,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`                  // 原价（元，可选）
	Condition     Condition              `protobuf:"varint,3,opt,name=condition,proto3,enum=pb.Condition" json:"condition,omitempty"`                              // 成色
	TradeMethod   TradeMethod            `protobuf:"varint,4,opt,name=trade_method,json=tradeMethod,proto3,enum=pb.TradeMethod" json:"trade_method,omitempty"`     // 交易方式
	ItemCategory  ItemCategory           `protobuf:"varint,5,opt,name=item_category,json=itemCategory,proto3,enum=pb.ItemCategory" json:"item_category,omitempty"` // 物品分类
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecondHandExtra) Reset() {
	*x = SecondHandExtra{}
	mi := &file_PB_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecondHandExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondHandExtra) ProtoMessage() {}

func (x *SecondHandExtra) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondHandExtra.ProtoReflect.Descriptor instead.
func (*SecondHandExtra) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{1}
}

func (x *SecondHandExtra) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SecondHandExtra) GetOriginalPrice() float64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *SecondHandExtra) GetCondition() Condition {
	if x != nil {
		return x.Condition
	}
	return Condition_CONDITION_UNSPECIFIED
}

func (x *SecondHandExtra) GetTradeMethod() TradeMethod {
	if x != nil {
		return x.TradeMethod
	}
	return TradeMethod_TRADE_METHOD_UNSPECIFIED
}

func (x *SecondHandExtra) GetItemCategory() ItemCategory {
	if x != nil {
		return x.ItemCategory
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

// 帖子消息（基础字段 + 业务扩展）
type Post struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SchoolId     int64                  `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"` // 多租户隔离键
	UserId       int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 发帖用户
	Type         PostType               `protobuf:"varint,4,opt,name=type,proto3,enum=pb.PostType" json:"type,omitempty"`
	Title        string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content      string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Images       []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"` // 图片 CDN URL 数组
	Status       PostStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=pb.PostStatus" json:"status,omitempty"`
	LikesCount   int32                  `protobuf:"varint,9,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	CommentCount int32                  `protobuf:"varint,10,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CreatedAt    int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix 时间戳（秒）
	UpdatedAt    int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiredAt    int64                  `protobuf:"varint,13,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // 过期时间（可选）
	// 业务扩展字段（按 type 取对应字段）
	LostFound     *LostFoundExtra  `protobuf:"bytes,20,opt,name=lost_found,json=lostFound,proto3" json:"lost_found,omitempty"`
	SecondHand    *SecondHandExtra `protobuf:"bytes,21,opt,name=second_hand,json=secondHand,proto3" json:"second_hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_PB_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{2}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *Post) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Post) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_POST_TYPE_UNSPECIFIED
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Post) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

func (x *Post) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *Post) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Post) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Post) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *Post) GetLostFound() *LostFoundExtra {
	if x != nil {
		return x.LostFound
	}
	return nil
}

func (x *Post) GetSecondHand() *SecondHandExtra {
	if x != nil {
		return x.SecondHand
	}
	return nil
}

// 评论消息
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SchoolId      int64                  `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                    // 评论内容（1-500 字）
	ParentId      int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 父评论ID（Phase 2 二级回复使用）
	Status        CommentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=pb.CommentStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_PB_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{3}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *Comment) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Comment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetStatus() CommentStatus {
	if x != nil {
		return x.Status
	}
	return CommentStatus_COMMENT_STATUS_UNSPECIFIED
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// DFA 敏感词命中详情
type SensitiveWordHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`      // 命中的敏感词
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`   // 起始位置（字符索引）
	End           int32                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`       // 结束位置
	Length        int32                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"` // 长度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensitiveWordHit) Reset() {
	*x = SensitiveWordHit{}
	mi := &file_PB_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensitiveWordHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveWordHit) ProtoMessage() {}

func (x *SensitiveWordHit) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveWordHit.ProtoReflect.Descriptor instead.
func (*SensitiveWordHit) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{4}
}

func (x *SensitiveWordHit) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *SensitiveWordHit) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SensitiveWordHit) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *SensitiveWordHit) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// 敏感词错误响应
type SensitiveWordError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Hits          []*SensitiveWordHit    `protobuf:"bytes,2,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensitiveWordError) Reset() {
	*x = SensitiveWordError{}
	mi := &file_PB_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensitiveWordError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensitiveWordError) ProtoMessage() {}

func (x *SensitiveWordError) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensitiveWordError.ProtoReflect.Descriptor instead.
func (*SensitiveWordError) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{5}
}

func (x *SensitiveWordError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SensitiveWordError) GetHits() []*SensitiveWordHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type CreatePostRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SchoolId int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"` // 强制注入（多租户隔离）
	UserId   int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 强制注入（从 JWT）
	Type     PostType               `protobuf:"varint,3,opt,name=type,proto3,enum=pb.PostType" json:"type,omitempty"`        // 帖子类型
	Title    string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                        // 标题（1-200 字）
	Content  string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                    // 正文（1-5000 字）
	Images   []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`                      // 图片 URL 列表
	// 业务扩展字段（根据 type 选择性填写）
	LostFound     *LostFoundExtra  `protobuf:"bytes,10,opt,name=lost_found,json=lostFound,proto3" json:"lost_found,omitempty"`
	SecondHand    *SecondHandExtra `protobuf:"bytes,11,opt,name=second_hand,json=secondHand,proto3" json:"second_hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_PB_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *CreatePostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePostRequest) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_POST_TYPE_UNSPECIFIED
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreatePostRequest) GetLostFound() *LostFoundExtra {
	if x != nil {
		return x.LostFound
	}
	return nil
}

func (x *CreatePostRequest) GetSecondHand() *SecondHandExtra {
	if x != nil {
		return x.SecondHand
	}
	return nil
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Status        PostStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=pb.PostStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_PB_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePostResponse) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePostResponse) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

func (x *CreatePostResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ViewerUserId  int64                  `protobuf:"varint,3,opt,name=viewer_user_id,json=viewerUserId,proto3" json:"viewer_user_id,omitempty"` // 查看者ID（用于判断点赞状态等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_PB_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *GetPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostRequest) GetViewerUserId() int64 {
	if x != nil {
		return x.ViewerUserId
	}
	return 0
}

type GetPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	IsLiked       bool                   `protobuf:"varint,2,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"` // 当前用户是否已点赞
	IsOwner       bool                   `protobuf:"varint,3,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"` // 当前用户是否为作者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_PB_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{9}
}

func (x *GetPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *GetPostResponse) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *GetPostResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type UpdatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 校验权限：仅作者本人
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Images        []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	LostFound     *LostFoundExtra        `protobuf:"bytes,10,opt,name=lost_found,json=lostFound,proto3" json:"lost_found,omitempty"`
	SecondHand    *SecondHandExtra       `protobuf:"bytes,11,opt,name=second_hand,json=secondHand,proto3" json:"second_hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostRequest) Reset() {
	*x = UpdatePostRequest{}
	mi := &file_PB_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRequest) ProtoMessage() {}

func (x *UpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *UpdatePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdatePostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdatePostRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdatePostRequest) GetLostFound() *LostFoundExtra {
	if x != nil {
		return x.LostFound
	}
	return nil
}

func (x *UpdatePostRequest) GetSecondHand() *SecondHandExtra {
	if x != nil {
		return x.SecondHand
	}
	return nil
}

type UpdatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostResponse) Reset() {
	*x = UpdatePostResponse{}
	mi := &file_PB_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostResponse) ProtoMessage() {}

func (x *UpdatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 作者本人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_PB_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *DeletePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *DeletePostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_PB_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPostsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	SchoolId      int64                          `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`      // 强制注入
	Type          PostType                       `protobuf:"varint,2,opt,name=type,proto3,enum=pb.PostType" json:"type,omitempty"`             // 帖子类型筛选（可选）
	Category      ItemCategory                   `protobuf:"varint,3,opt,name=category,proto3,enum=pb.ItemCategory" json:"category,omitempty"` // 物品分类筛选（可选）
	Status        PostStatus                     `protobuf:"varint,4,opt,name=status,proto3,enum=pb.PostStatus" json:"status,omitempty"`       // 状态筛选（默认 published）
	Pagination    *common_pb.CursorPaginationReq `protobuf:"bytes,5,opt,name=pagination,proto3" json:"pagination,omitempty"`                   // 游标分页
	Sort          common_pb.SortType             `protobuf:"varint,6,opt,name=sort,proto3,enum=pb.SortType" json:"sort,omitempty"`             // 排序方式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRequest) Reset() {
	*x = ListPostsRequest{}
	mi := &file_PB_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRequest) ProtoMessage() {}

func (x *ListPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRequest.ProtoReflect.Descriptor instead.
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{14}
}

func (x *ListPostsRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *ListPostsRequest) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_POST_TYPE_UNSPECIFIED
}

func (x *ListPostsRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *ListPostsRequest) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

func (x *ListPostsRequest) GetPagination() *common_pb.CursorPaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPostsRequest) GetSort() common_pb.SortType {
	if x != nil {
		return x.Sort
	}
	return common_pb.SortType(0)
}

type ListPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsResponse) Reset() {
	*x = ListPostsResponse{}
	mi := &file_PB_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsResponse) ProtoMessage() {}

func (x *ListPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsResponse.ProtoReflect.Descriptor instead.
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{15}
}

func (x *ListPostsResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListPostsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListPostsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"` // 1-500 字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_PB_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommentRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *CreateCommentRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreateCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_PB_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCommentResponse) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CreateCommentResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	CommentId     int64                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 仅作者本人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_PB_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteCommentRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *DeleteCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_PB_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	SchoolId      int64                          `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                          `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Pagination    *common_pb.CursorPaginationReq `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_PB_content_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{20}
}

func (x *ListCommentsRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *ListCommentsRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *ListCommentsRequest) GetPagination() *common_pb.CursorPaginationReq {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_PB_content_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{21}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListCommentsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type LikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostRequest) Reset() {
	*x = LikePostRequest{}
	mi := &file_PB_content_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostRequest) ProtoMessage() {}

func (x *LikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostRequest.ProtoReflect.Descriptor instead.
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{22}
}

func (x *LikePostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *LikePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *LikePostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	LikesCount    int32                  `protobuf:"varint,2,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"` // 当前点赞总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikePostResponse) Reset() {
	*x = LikePostResponse{}
	mi := &file_PB_content_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikePostResponse) ProtoMessage() {}

func (x *LikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikePostResponse.ProtoReflect.Descriptor instead.
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{23}
}

func (x *LikePostResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *LikePostResponse) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type UnlikePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostRequest) Reset() {
	*x = UnlikePostRequest{}
	mi := &file_PB_content_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostRequest) ProtoMessage() {}

func (x *UnlikePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostRequest.ProtoReflect.Descriptor instead.
func (*UnlikePostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{24}
}

func (x *UnlikePostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *UnlikePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UnlikePostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnlikePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	LikesCount    int32                  `protobuf:"varint,2,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikePostResponse) Reset() {
	*x = UnlikePostResponse{}
	mi := &file_PB_content_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikePostResponse) ProtoMessage() {}

func (x *UnlikePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikePostResponse.ProtoReflect.Descriptor instead.
func (*UnlikePostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{25}
}

func (x *UnlikePostResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *UnlikePostResponse) GetLikesCount() int32 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

type SearchContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`      // 强制注入
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`                         // 搜索关键词（标题^3 + 内容）
	Type          PostType               `protobuf:"varint,3,opt,name=type,proto3,enum=pb.PostType" json:"type,omitempty"`             // 帖子类型筛选
	Category      ItemCategory           `protobuf:"varint,4,opt,name=category,proto3,enum=pb.ItemCategory" json:"category,omitempty"` // 物品分类筛选
	Status        PostStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=pb.PostStatus" json:"status,omitempty"`       // 默认 published
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`                              // 页码（从 1 开始）
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`      // 默认 20，最大 100
	Sort          common_pb.SortType     `protobuf:"varint,8,opt,name=sort,proto3,enum=pb.SortType" json:"sort,omitempty"`             // 排序方式（默认 relevance）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentRequest) Reset() {
	*x = SearchContentRequest{}
	mi := &file_PB_content_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentRequest) ProtoMessage() {}

func (x *SearchContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentRequest.ProtoReflect.Descriptor instead.
func (*SearchContentRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{26}
}

func (x *SearchContentRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *SearchContentRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchContentRequest) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_POST_TYPE_UNSPECIFIED
}

func (x *SearchContentRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *SearchContentRequest) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

func (x *SearchContentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchContentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchContentRequest) GetSort() common_pb.SortType {
	if x != nil {
		return x.Sort
	}
	return common_pb.SortType(0)
}

type SearchContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TookMs        int64                  `protobuf:"varint,5,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"` // ES 查询耗时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentResponse) Reset() {
	*x = SearchContentResponse{}
	mi := &file_PB_content_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentResponse) ProtoMessage() {}

func (x *SearchContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentResponse.ProtoReflect.Descriptor instead.
func (*SearchContentResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{27}
}

func (x *SearchContentResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *SearchContentResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchContentResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchContentResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchContentResponse) GetTookMs() int64 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

type ApprovePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ReviewerId    int64                  `protobuf:"varint,3,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"` // 审核员ID
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`                          // 审核备注（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePostRequest) Reset() {
	*x = ApprovePostRequest{}
	mi := &file_PB_content_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePostRequest) ProtoMessage() {}

func (x *ApprovePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePostRequest.ProtoReflect.Descriptor instead.
func (*ApprovePostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{28}
}

func (x *ApprovePostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *ApprovePostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *ApprovePostRequest) GetReviewerId() int64 {
	if x != nil {
		return x.ReviewerId
	}
	return 0
}

func (x *ApprovePostRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ApprovePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewStatus     PostStatus             `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=pb.PostStatus" json:"new_status,omitempty"` // 应为 PUBLISHED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePostResponse) Reset() {
	*x = ApprovePostResponse{}
	mi := &file_PB_content_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePostResponse) ProtoMessage() {}

func (x *ApprovePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePostResponse.ProtoReflect.Descriptor instead.
func (*ApprovePostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{29}
}

func (x *ApprovePostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApprovePostResponse) GetNewStatus() PostStatus {
	if x != nil {
		return x.NewStatus
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

type RejectPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ReviewerId    int64                  `protobuf:"varint,3,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // 拒绝原因（必填，用于通知用户）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectPostRequest) Reset() {
	*x = RejectPostRequest{}
	mi := &file_PB_content_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPostRequest) ProtoMessage() {}

func (x *RejectPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPostRequest.ProtoReflect.Descriptor instead.
func (*RejectPostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{30}
}

func (x *RejectPostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *RejectPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *RejectPostRequest) GetReviewerId() int64 {
	if x != nil {
		return x.ReviewerId
	}
	return 0
}

func (x *RejectPostRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewStatus     PostStatus             `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=pb.PostStatus" json:"new_status,omitempty"` // 应为 REJECTED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectPostResponse) Reset() {
	*x = RejectPostResponse{}
	mi := &file_PB_content_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPostResponse) ProtoMessage() {}

func (x *RejectPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPostResponse.ProtoReflect.Descriptor instead.
func (*RejectPostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{31}
}

func (x *RejectPostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RejectPostResponse) GetNewStatus() PostStatus {
	if x != nil {
		return x.NewStatus
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

type TakedownPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ReviewerId    int64                  `protobuf:"varint,3,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // 下架原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakedownPostRequest) Reset() {
	*x = TakedownPostRequest{}
	mi := &file_PB_content_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakedownPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakedownPostRequest) ProtoMessage() {}

func (x *TakedownPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakedownPostRequest.ProtoReflect.Descriptor instead.
func (*TakedownPostRequest) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{32}
}

func (x *TakedownPostRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *TakedownPostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *TakedownPostRequest) GetReviewerId() int64 {
	if x != nil {
		return x.ReviewerId
	}
	return 0
}

func (x *TakedownPostRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TakedownPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewStatus     PostStatus             `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=pb.PostStatus" json:"new_status,omitempty"` // 应为 CLOSED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakedownPostResponse) Reset() {
	*x = TakedownPostResponse{}
	mi := &file_PB_content_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakedownPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakedownPostResponse) ProtoMessage() {}

func (x *TakedownPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_content_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakedownPostResponse.ProtoReflect.Descriptor instead.
func (*TakedownPostResponse) Descriptor() ([]byte, []int) {
	return file_PB_content_proto_rawDescGZIP(), []int{33}
}

func (x *TakedownPostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TakedownPostResponse) GetNewStatus() PostStatus {
	if x != nil {
		return x.NewStatus
	}
	return PostStatus_POST_STATUS_UNSPECIFIED
}

var File_PB_content_proto protoreflect.FileDescriptor

const file_PB_content_proto_rawDesc = "" +
	"\n" +
	"\x10PB/content.proto\x12\x02pb\x1a\x0fPB/common.proto\"\xb6\x01\n" +
	"\x0eLostFoundExtra\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x125\n" +
	"\ritem_category\x18\x02 \x01(\x0e2\x10.pb.ItemCategoryR\fitemCategory\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\x127\n" +
	"\rlost_or_found\x18\x04 \x01(\x0e2\x13.pb.LostOrFoundTypeR\vlostOrFound\"\xe6\x01\n" +
	"\x0fSecondHandExtra\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12%\n" +
	"\x0eoriginal_price\x18\x02 \x01(\x01R\roriginalPrice\x12+\n" +
	"\tcondition\x18\x03 \x01(\x0e2\r.pb.ConditionR\tcondition\x122\n" +
	"\ftrade_method\x18\x04 \x01(\x0e2\x0f.pb.TradeMethodR\vtradeMethod\x125\n" +
	"\ritem_category\x18\x05 \x01(\x0e2\x10.pb.ItemCategoryR\fitemCategory\"\xea\x03\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tschool_id\x18\x02 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12 \n" +
	"\x04type\x18\x04 \x01(\x0e2\f.pb.PostTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12&\n" +
	"\x06status\x18\b \x01(\x0e2\x0e.pb.PostStatusR\x06status\x12\x1f\n" +
	"\vlikes_count\x18\t \x01(\x05R\n" +
	"likesCount\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\x05R\fcommentCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expired_at\x18\r \x01(\x03R\texpiredAt\x121\n" +
	"\n" +
	"lost_found\x18\x14 \x01(\v2\x12.pb.LostFoundExtraR\tlostFound\x124\n" +
	"\vsecond_hand\x18\x15 \x01(\v2\x13.pb.SecondHandExtraR\n" +
	"secondHand\"\xe9\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tschool_id\x18\x02 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12)\n" +
	"\x06status\x18\a \x01(\x0e2\x11.pb.CommentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"f\n" +
	"\x10SensitiveWordHit\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x05R\x06length\"X\n" +
	"\x12SensitiveWordError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12(\n" +
	"\x04hits\x18\x02 \x03(\v2\x14.pb.SensitiveWordHitR\x04hits\"\x9c\x02\n" +
	"\x11CreatePostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12 \n" +
	"\x04type\x18\x03 \x01(\x0e2\f.pb.PostTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x121\n" +
	"\n" +
	"lost_found\x18\n" +
	" \x01(\v2\x12.pb.LostFoundExtraR\tlostFound\x124\n" +
	"\vsecond_hand\x18\v \x01(\v2\x13.pb.SecondHandExtraR\n" +
	"secondHand\"t\n" +
	"\x12CreatePostResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.pb.PostStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"l\n" +
	"\x0eGetPostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12$\n" +
	"\x0eviewer_user_id\x18\x03 \x01(\x03R\fviewerUserId\"e\n" +
	"\x0fGetPostResponse\x12\x1c\n" +
	"\x04post\x18\x01 \x01(\v2\b.pb.PostR\x04post\x12\x19\n" +
	"\bis_liked\x18\x02 \x01(\bR\aisLiked\x12\x19\n" +
	"\bis_owner\x18\x03 \x01(\bR\aisOwner\"\x93\x02\n" +
	"\x11UpdatePostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x121\n" +
	"\n" +
	"lost_found\x18\n" +
	" \x01(\v2\x12.pb.LostFoundExtraR\tlostFound\x124\n" +
	"\vsecond_hand\x18\v \x01(\v2\x13.pb.SecondHandExtraR\n" +
	"secondHand\".\n" +
	"\x12UpdatePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x11DeletePostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\".\n" +
	"\x12DeletePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x82\x02\n" +
	"\x10ListPostsRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12 \n" +
	"\x04type\x18\x02 \x01(\x0e2\f.pb.PostTypeR\x04type\x12,\n" +
	"\bcategory\x18\x03 \x01(\x0e2\x10.pb.ItemCategoryR\bcategory\x12&\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0e.pb.PostStatusR\x06status\x127\n" +
	"\n" +
	"pagination\x18\x05 \x01(\v2\x17.pb.CursorPaginationReqR\n" +
	"pagination\x12 \n" +
	"\x04sort\x18\x06 \x01(\x0e2\f.pb.SortTypeR\x04sort\"o\n" +
	"\x11ListPostsResponse\x12\x1e\n" +
	"\x05posts\x18\x01 \x03(\v2\b.pb.PostR\x05posts\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x7f\n" +
	"\x14CreateCommentRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"U\n" +
	"\x15CreateCommentResponse\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"k\n" +
	"\x14DeleteCommentRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"1\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x84\x01\n" +
	"\x13ListCommentsRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.pb.CursorPaginationReqR\n" +
	"pagination\"{\n" +
	"\x14ListCommentsResponse\x12'\n" +
	"\bcomments\x18\x01 \x03(\v2\v.pb.CommentR\bcomments\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"`\n" +
	"\x0fLikePostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"I\n" +
	"\x10LikePostResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1f\n" +
	"\vlikes_count\x18\x02 \x01(\x05R\n" +
	"likesCount\"b\n" +
	"\x11UnlikePostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"K\n" +
	"\x12UnlikePostResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x1f\n" +
	"\vlikes_count\x18\x02 \x01(\x05R\n" +
	"likesCount\"\x98\x02\n" +
	"\x14SearchContentRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12 \n" +
	"\x04type\x18\x03 \x01(\x0e2\f.pb.PostTypeR\x04type\x12,\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x10.pb.ItemCategoryR\bcategory\x12&\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0e.pb.PostStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12 \n" +
	"\x04sort\x18\b \x01(\x0e2\f.pb.SortTypeR\x04sort\"\x97\x01\n" +
	"\x15SearchContentResponse\x12\x1e\n" +
	"\x05posts\x18\x01 \x03(\v2\b.pb.PostR\x05posts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x17\n" +
	"\atook_ms\x18\x05 \x01(\x03R\x06tookMs\"\x85\x01\n" +
	"\x12ApprovePostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1f\n" +
	"\vreviewer_id\x18\x03 \x01(\x03R\n" +
	"reviewerId\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"^\n" +
	"\x13ApprovePostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x0e.pb.PostStatusR\tnewStatus\"\x82\x01\n" +
	"\x11RejectPostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1f\n" +
	"\vreviewer_id\x18\x03 \x01(\x03R\n" +
	"reviewerId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"]\n" +
	"\x12RejectPostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x0e.pb.PostStatusR\tnewStatus\"\x84\x01\n" +
	"\x13TakedownPostRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1f\n" +
	"\vreviewer_id\x18\x03 \x01(\x03R\n" +
	"reviewerId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"_\n" +
	"\x14TakedownPostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x0e.pb.PostStatusR\tnewStatus*q\n" +
	"\bPostType\x12\x19\n" +
	"\x15POST_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POST_TYPE_GENERAL\x10\x01\x12\x18\n" +
	"\x14POST_TYPE_LOST_FOUND\x10\x02\x12\x19\n" +
	"\x15POST_TYPE_SECOND_HAND\x10\x03*\xd9\x01\n" +
	"\n" +
	"PostStatus\x12\x1b\n" +
	"\x17POST_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POST_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15POST_STATUS_PUBLISHED\x10\x02\x12\x17\n" +
	"\x13POST_STATUS_EXPIRED\x10\x03\x12\x16\n" +
	"\x12POST_STATUS_CLOSED\x10\x04\x12\x18\n" +
	"\x14POST_STATUS_REJECTED\x10\x05\x12\x19\n" +
	"\x15POST_STATUS_RETRIEVED\x10\x06\x12\x14\n" +
	"\x10POST_STATUS_SOLD\x10\a*\xff\x01\n" +
	"\fItemCategory\x12\x1d\n" +
	"\x19ITEM_CATEGORY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ITEM_CATEGORY_DIGITAL\x10\x01\x12\x1d\n" +
	"\x19ITEM_CATEGORY_CERTIFICATE\x10\x02\x12\x15\n" +
	"\x11ITEM_CATEGORY_KEY\x10\x03\x12\x16\n" +
	"\x12ITEM_CATEGORY_BOOK\x10\x04\x12\x1a\n" +
	"\x16ITEM_CATEGORY_CLOTHING\x10\x05\x12\x19\n" +
	"\x15ITEM_CATEGORY_CHARGER\x10\x06\x12\x17\n" +
	"\x13ITEM_CATEGORY_DAILY\x10\a\x12\x17\n" +
	"\x13ITEM_CATEGORY_OTHER\x10\b*\x7f\n" +
	"\tCondition\x12\x19\n" +
	"\x15CONDITION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CONDITION_BRAND_NEW\x10\x01\x12\x16\n" +
	"\x12CONDITION_LIKE_NEW\x10\x02\x12\x12\n" +
	"\x0eCONDITION_GOOD\x10\x03\x12\x12\n" +
	"\x0eCONDITION_FAIR\x10\x04*e\n" +
	"\vTradeMethod\x12\x1c\n" +
	"\x18TRADE_METHOD_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRADE_METHOD_FACE_TO_FACE\x10\x01\x12\x19\n" +
	"\x15TRADE_METHOD_DELIVERY\x10\x02*a\n" +
	"\x0fLostOrFoundType\x12\x1d\n" +
	"\x19LOST_OR_FOUND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LOST_OR_FOUND_LOST\x10\x01\x12\x17\n" +
	"\x13LOST_OR_FOUND_FOUND\x10\x02*f\n" +
	"\rCommentStatus\x12\x1e\n" +
	"\x1aCOMMENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMMENT_STATUS_NORMAL\x10\x01\x12\x1a\n" +
	"\x16COMMENT_STATUS_DELETED\x10\x022\xfe\x06\n" +
	"\x0eContentService\x12;\n" +
	"\n" +
	"CreatePost\x12\x15.pb.CreatePostRequest\x1a\x16.pb.CreatePostResponse\x122\n" +
	"\aGetPost\x12\x12.pb.GetPostRequest\x1a\x13.pb.GetPostResponse\x12;\n" +
	"\n" +
	"UpdatePost\x12\x15.pb.UpdatePostRequest\x1a\x16.pb.UpdatePostResponse\x12;\n" +
	"\n" +
	"DeletePost\x12\x15.pb.DeletePostRequest\x1a\x16.pb.DeletePostResponse\x128\n" +
	"\tListPosts\x12\x14.pb.ListPostsRequest\x1a\x15.pb.ListPostsResponse\x12D\n" +
	"\rCreateComment\x12\x18.pb.CreateCommentRequest\x1a\x19.pb.CreateCommentResponse\x12D\n" +
	"\rDeleteComment\x12\x18.pb.DeleteCommentRequest\x1a\x19.pb.DeleteCommentResponse\x12A\n" +
	"\fListComments\x12\x17.pb.ListCommentsRequest\x1a\x18.pb.ListCommentsResponse\x125\n" +
	"\bLikePost\x12\x13.pb.LikePostRequest\x1a\x14.pb.LikePostResponse\x12;\n" +
	"\n" +
	"UnlikePost\x12\x15.pb.UnlikePostRequest\x1a\x16.pb.UnlikePostResponse\x12D\n" +
	"\rSearchContent\x12\x18.pb.SearchContentRequest\x1a\x19.pb.SearchContentResponse\x12>\n" +
	"\vApprovePost\x12\x16.pb.ApprovePostRequest\x1a\x17.pb.ApprovePostResponse\x12;\n" +
	"\n" +
	"RejectPost\x12\x15.pb.RejectPostRequest\x1a\x16.pb.RejectPostResponse\x12A\n" +
	"\fTakedownPost\x12\x17.pb.TakedownPostRequest\x1a\x18.pb.TakedownPostResponseB*Z(go_projects/praProject1/PB/pb/content_pbb\x06proto3"

var (
	file_PB_content_proto_rawDescOnce sync.Once
	file_PB_content_proto_rawDescData []byte
)

func file_PB_content_proto_rawDescGZIP() []byte {
	file_PB_content_proto_rawDescOnce.Do(func() {
		file_PB_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_content_proto_rawDesc), len(file_PB_content_proto_rawDesc)))
	})
	return file_PB_content_proto_rawDescData
}

var file_PB_content_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_PB_content_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_PB_content_proto_goTypes = []any{
	(PostType)(0),                         // 0: pb.PostType
	(PostStatus)(0),                       // 1: pb.PostStatus
	(ItemCategory)(0),                     // 2: pb.ItemCategory
	(Condition)(0),                        // 3: pb.Condition
	(TradeMethod)(0),                      // 4: pb.TradeMethod
	(LostOrFoundType)(0),                  // 5: pb.LostOrFoundType
	(CommentStatus)(0),                    // 6: pb.CommentStatus
	(*LostFoundExtra)(nil),                // 7: pb.LostFoundExtra
	(*SecondHandExtra)(nil),               // 8: pb.SecondHandExtra
	(*Post)(nil),                          // 9: pb.Post
	(*Comment)(nil),                       // 10: pb.Comment
	(*SensitiveWordHit)(nil),              // 11: pb.SensitiveWordHit
	(*SensitiveWordError)(nil),            // 12: pb.SensitiveWordError
	(*CreatePostRequest)(nil),             // 13: pb.CreatePostRequest
	(*CreatePostResponse)(nil),            // 14: pb.CreatePostResponse
	(*GetPostRequest)(nil),                // 15: pb.GetPostRequest
	(*GetPostResponse)(nil),               // 16: pb.GetPostResponse
	(*UpdatePostRequest)(nil),             // 17: pb.UpdatePostRequest
	(*UpdatePostResponse)(nil),            // 18: pb.UpdatePostResponse
	(*DeletePostRequest)(nil),             // 19: pb.DeletePostRequest
	(*DeletePostResponse)(nil),            // 20: pb.DeletePostResponse
	(*ListPostsRequest)(nil),              // 21: pb.ListPostsRequest
	(*ListPostsResponse)(nil),             // 22: pb.ListPostsResponse
	(*CreateCommentRequest)(nil),          // 23: pb.CreateCommentRequest
	(*CreateCommentResponse)(nil),         // 24: pb.CreateCommentResponse
	(*DeleteCommentRequest)(nil),          // 25: pb.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),         // 26: pb.DeleteCommentResponse
	(*ListCommentsRequest)(nil),           // 27: pb.ListCommentsRequest
	(*ListCommentsResponse)(nil),          // 28: pb.ListCommentsResponse
	(*LikePostRequest)(nil),               // 29: pb.LikePostRequest
	(*LikePostResponse)(nil),              // 30: pb.LikePostResponse
	(*UnlikePostRequest)(nil),             // 31: pb.UnlikePostRequest
	(*UnlikePostResponse)(nil),            // 32: pb.UnlikePostResponse
	(*SearchContentRequest)(nil),          // 33: pb.SearchContentRequest
	(*SearchContentResponse)(nil),         // 34: pb.SearchContentResponse
	(*ApprovePostRequest)(nil),            // 35: pb.ApprovePostRequest
	(*ApprovePostResponse)(nil),           // 36: pb.ApprovePostResponse
	(*RejectPostRequest)(nil),             // 37: pb.RejectPostRequest
	(*RejectPostResponse)(nil),            // 38: pb.RejectPostResponse
	(*TakedownPostRequest)(nil),           // 39: pb.TakedownPostRequest
	(*TakedownPostResponse)(nil),          // 40: pb.TakedownPostResponse
	(*common_pb.CursorPaginationReq)(nil), // 41: pb.CursorPaginationReq
	(common_pb.SortType)(0),               // 42: pb.SortType
}
var file_PB_content_proto_depIdxs = []int32{
	2,  // 0: pb.LostFoundExtra.item_category:type_name -> pb.ItemCategory
	5,  // 1: pb.LostFoundExtra.lost_or_found:type_name -> pb.LostOrFoundType
	3,  // 2: pb.SecondHandExtra.condition:type_name -> pb.Condition
	4,  // 3: pb.SecondHandExtra.trade_method:type_name -> pb.TradeMethod
	2,  // 4: pb.SecondHandExtra.item_category:type_name -> pb.ItemCategory
	0,  // 5: pb.Post.type:type_name -> pb.PostType
	1,  // 6: pb.Post.status:type_name -> pb.PostStatus
	7,  // 7: pb.Post.lost_found:type_name -> pb.LostFoundExtra
	8,  // 8: pb.Post.second_hand:type_name -> pb.SecondHandExtra
	6,  // 9: pb.Comment.status:type_name -> pb.CommentStatus
	11, // 10: pb.SensitiveWordError.hits:type_name -> pb.SensitiveWordHit
	0,  // 11: pb.CreatePostRequest.type:type_name -> pb.PostType
	7,  // 12: pb.CreatePostRequest.lost_found:type_name -> pb.LostFoundExtra
	8,  // 13: pb.CreatePostRequest.second_hand:type_name -> pb.SecondHandExtra
	1,  // 14: pb.CreatePostResponse.status:type_name -> pb.PostStatus
	9,  // 15: pb.GetPostResponse.post:type_name -> pb.Post
	7,  // 16: pb.UpdatePostRequest.lost_found:type_name -> pb.LostFoundExtra
	8,  // 17: pb.UpdatePostRequest.second_hand:type_name -> pb.SecondHandExtra
	0,  // 18: pb.ListPostsRequest.type:type_name -> pb.PostType
	2,  // 19: pb.ListPostsRequest.category:type_name -> pb.ItemCategory
	1,  // 20: pb.ListPostsRequest.status:type_name -> pb.PostStatus
	41, // 21: pb.ListPostsRequest.pagination:type_name -> pb.CursorPaginationReq
	42, // 22: pb.ListPostsRequest.sort:type_name -> pb.SortType
	9,  // 23: pb.ListPostsResponse.posts:type_name -> pb.Post
	41, // 24: pb.ListCommentsRequest.pagination:type_name -> pb.CursorPaginationReq
	10, // 25: pb.ListCommentsResponse.comments:type_name -> pb.Comment
	0,  // 26: pb.SearchContentRequest.type:type_name -> pb.PostType
	2,  // 27: pb.SearchContentRequest.category:type_name -> pb.ItemCategory
	1,  // 28: pb.SearchContentRequest.status:type_name -> pb.PostStatus
	42, // 29: pb.SearchContentRequest.sort:type_name -> pb.SortType
	9,  // 30: pb.SearchContentResponse.posts:type_name -> pb.Post
	1,  // 31: pb.ApprovePostResponse.new_status:type_name -> pb.PostStatus
	1,  // 32: pb.RejectPostResponse.new_status:type_name -> pb.PostStatus
	1,  // 33: pb.TakedownPostResponse.new_status:type_name -> pb.PostStatus
	13, // 34: pb.ContentService.CreatePost:input_type -> pb.CreatePostRequest
	15, // 35: pb.ContentService.GetPost:input_type -> pb.GetPostRequest
	17, // 36: pb.ContentService.UpdatePost:input_type -> pb.UpdatePostRequest
	19, // 37: pb.ContentService.DeletePost:input_type -> pb.DeletePostRequest
	21, // 38: pb.ContentService.ListPosts:input_type -> pb.ListPostsRequest
	23, // 39: pb.ContentService.CreateComment:input_type -> pb.CreateCommentRequest
	25, // 40: pb.ContentService.DeleteComment:input_type -> pb.DeleteCommentRequest
	27, // 41: pb.ContentService.ListComments:input_type -> pb.ListCommentsRequest
	29, // 42: pb.ContentService.LikePost:input_type -> pb.LikePostRequest
	31, // 43: pb.ContentService.UnlikePost:input_type -> pb.UnlikePostRequest
	33, // 44: pb.ContentService.SearchContent:input_type -> pb.SearchContentRequest
	35, // 45: pb.ContentService.ApprovePost:input_type -> pb.ApprovePostRequest
	37, // 46: pb.ContentService.RejectPost:input_type -> pb.RejectPostRequest
	39, // 47: pb.ContentService.TakedownPost:input_type -> pb.TakedownPostRequest
	14, // 48: pb.ContentService.CreatePost:output_type -> pb.CreatePostResponse
	16, // 49: pb.ContentService.GetPost:output_type -> pb.GetPostResponse
	18, // 50: pb.ContentService.UpdatePost:output_type -> pb.UpdatePostResponse
	20, // 51: pb.ContentService.DeletePost:output_type -> pb.DeletePostResponse
	22, // 52: pb.ContentService.ListPosts:output_type -> pb.ListPostsResponse
	24, // 53: pb.ContentService.CreateComment:output_type -> pb.CreateCommentResponse
	26, // 54: pb.ContentService.DeleteComment:output_type -> pb.DeleteCommentResponse
	28, // 55: pb.ContentService.ListComments:output_type -> pb.ListCommentsResponse
	30, // 56: pb.ContentService.LikePost:output_type -> pb.LikePostResponse
	32, // 57: pb.ContentService.UnlikePost:output_type -> pb.UnlikePostResponse
	34, // 58: pb.ContentService.SearchContent:output_type -> pb.SearchContentResponse
	36, // 59: pb.ContentService.ApprovePost:output_type -> pb.ApprovePostResponse
	38, // 60: pb.ContentService.RejectPost:output_type -> pb.RejectPostResponse
	40, // 61: pb.ContentService.TakedownPost:output_type -> pb.TakedownPostResponse
	48, // [48:62] is the sub-list for method output_type
	34, // [34:48] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_PB_content_proto_init() }
func file_PB_content_proto_init() {
	if File_PB_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_content_proto_rawDesc), len(file_PB_content_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PB_content_proto_goTypes,
		DependencyIndexes: file_PB_content_proto_depIdxs,
		EnumInfos:         file_PB_content_proto_enumTypes,
		MessageInfos:      file_PB_content_proto_msgTypes,
	}.Build()
	File_PB_content_proto = out.File
	file_PB_content_proto_goTypes = nil
	file_PB_content_proto_depIdxs = nil
}
