// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: PB/common.proto

package common_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 排序方式（通用）
type SortType int32

const (
	SortType_SORT_TYPE_UNSPECIFIED SortType = 0
	SortType_SORT_TYPE_TIME_DESC   SortType = 1 // 时间倒序（默认）
	SortType_SORT_TYPE_LIKES_DESC  SortType = 2 // 点赞数倒序
	SortType_SORT_TYPE_RELEVANCE   SortType = 3 // 相关度排序（搜索场景）
)

// Enum value maps for SortType.
var (
	SortType_name = map[int32]string{
		0: "SORT_TYPE_UNSPECIFIED",
		1: "SORT_TYPE_TIME_DESC",
		2: "SORT_TYPE_LIKES_DESC",
		3: "SORT_TYPE_RELEVANCE",
	}
	SortType_value = map[string]int32{
		"SORT_TYPE_UNSPECIFIED": 0,
		"SORT_TYPE_TIME_DESC":   1,
		"SORT_TYPE_LIKES_DESC":  2,
		"SORT_TYPE_RELEVANCE":   3,
	}
)

func (x SortType) Enum() *SortType {
	p := new(SortType)
	*p = x
	return p
}

func (x SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_common_proto_enumTypes[0].Descriptor()
}

func (SortType) Type() protoreflect.EnumType {
	return &file_PB_common_proto_enumTypes[0]
}

func (x SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortType.Descriptor instead.
func (SortType) EnumDescriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{0}
}

// 分页请求（传统页码方式，向后兼容）
type PaginationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 当前页码
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationReq) Reset() {
	*x = PaginationReq{}
	mi := &file_PB_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationReq) ProtoMessage() {}

func (x *PaginationReq) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationReq.ProtoReflect.Descriptor instead.
func (*PaginationReq) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{0}
}

func (x *PaginationReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 分页响应
type PaginationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"` // 总记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResp) Reset() {
	*x = PaginationResp{}
	mi := &file_PB_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResp) ProtoMessage() {}

func (x *PaginationResp) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResp.ProtoReflect.Descriptor instead.
func (*PaginationResp) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PaginationResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 游标分页请求（推荐用于无限下拉场景，性能稳定无重复漏数据）
type CursorPaginationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // 上次响应的 next_cursor，首次请求传空
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数（默认 20，最大 100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPaginationReq) Reset() {
	*x = CursorPaginationReq{}
	mi := &file_PB_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationReq) ProtoMessage() {}

func (x *CursorPaginationReq) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationReq.ProtoReflect.Descriptor instead.
func (*CursorPaginationReq) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{2}
}

func (x *CursorPaginationReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *CursorPaginationReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 游标分页响应
type CursorPaginationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 下次请求的 cursor，空表示已到末尾
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`         // 是否还有更多数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPaginationResp) Reset() {
	*x = CursorPaginationResp{}
	mi := &file_PB_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPaginationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPaginationResp) ProtoMessage() {}

func (x *CursorPaginationResp) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPaginationResp.ProtoReflect.Descriptor instead.
func (*CursorPaginationResp) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{3}
}

func (x *CursorPaginationResp) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *CursorPaginationResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 统一基础响应 (可选，通常 gRPC 推荐使用 status.Code，但业务层可自定义)
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_PB_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{4}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 学校上下文（多租户隔离核心字段，网关从 JWT 注入）
type SchoolContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"` // 学校ID（多租户隔离键）
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 当前操作用户ID
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`     // 全链路追踪ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolContext) Reset() {
	*x = SchoolContext{}
	mi := &file_PB_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolContext) ProtoMessage() {}

func (x *SchoolContext) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolContext.ProtoReflect.Descriptor instead.
func (*SchoolContext) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{5}
}

func (x *SchoolContext) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *SchoolContext) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SchoolContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// 通用空请求（用于不需要参数的 RPC）
type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_PB_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{6}
}

// 通用 ID 请求
type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_PB_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_PB_common_proto_rawDescGZIP(), []int{7}
}

func (x *IdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_PB_common_proto protoreflect.FileDescriptor

const file_PB_common_proto_rawDesc = "" +
	"\n" +
	"\x0fPB/common.proto\x12\x02pb\"7\n" +
	"\rPaginationReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"N\n" +
	"\x0ePaginationResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"J\n" +
	"\x13CursorPaginationReq\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"R\n" +
	"\x14CursorPaginationResp\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"<\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\rSchoolContext\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"\x0e\n" +
	"\fEmptyRequest\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id*q\n" +
	"\bSortType\x12\x19\n" +
	"\x15SORT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SORT_TYPE_TIME_DESC\x10\x01\x12\x18\n" +
	"\x14SORT_TYPE_LIKES_DESC\x10\x02\x12\x17\n" +
	"\x13SORT_TYPE_RELEVANCE\x10\x03B)Z'go_projects/praProject1/PB/pb/common_pbb\x06proto3"

var (
	file_PB_common_proto_rawDescOnce sync.Once
	file_PB_common_proto_rawDescData []byte
)

func file_PB_common_proto_rawDescGZIP() []byte {
	file_PB_common_proto_rawDescOnce.Do(func() {
		file_PB_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_common_proto_rawDesc), len(file_PB_common_proto_rawDesc)))
	})
	return file_PB_common_proto_rawDescData
}

var file_PB_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PB_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_PB_common_proto_goTypes = []any{
	(SortType)(0),                // 0: pb.SortType
	(*PaginationReq)(nil),        // 1: pb.PaginationReq
	(*PaginationResp)(nil),       // 2: pb.PaginationResp
	(*CursorPaginationReq)(nil),  // 3: pb.CursorPaginationReq
	(*CursorPaginationResp)(nil), // 4: pb.CursorPaginationResp
	(*BaseResponse)(nil),         // 5: pb.BaseResponse
	(*SchoolContext)(nil),        // 6: pb.SchoolContext
	(*EmptyRequest)(nil),         // 7: pb.EmptyRequest
	(*IdRequest)(nil),            // 8: pb.IdRequest
}
var file_PB_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PB_common_proto_init() }
func file_PB_common_proto_init() {
	if File_PB_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_common_proto_rawDesc), len(file_PB_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PB_common_proto_goTypes,
		DependencyIndexes: file_PB_common_proto_depIdxs,
		EnumInfos:         file_PB_common_proto_enumTypes,
		MessageInfos:      file_PB_common_proto_msgTypes,
	}.Build()
	File_PB_common_proto = out.File
	file_PB_common_proto_goTypes = nil
	file_PB_common_proto_depIdxs = nil
}
