// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: PB/task.proto

package task_pb

import (
	common_pb "go_projects/praProject1/PB/pb/common_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_DELIVERY    TaskType = 1 // 跑腿
	TaskType_TASK_TYPE_CARPOOL     TaskType = 2 // 拼车
	TaskType_TASK_TYPE_BOUNTY      TaskType = 3 // 悬赏
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_DELIVERY",
		2: "TASK_TYPE_CARPOOL",
		3: "TASK_TYPE_BOUNTY",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_DELIVERY":    1,
		"TASK_TYPE_CARPOOL":     2,
		"TASK_TYPE_BOUNTY":      3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_PB_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_OPEN        TaskStatus = 1 // 待接单
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2 // 进行中
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3 // 已完成
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 4 // 已取消
	TaskStatus_TASK_STATUS_EXPIRED     TaskStatus = 5 // 已过期
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_OPEN",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_CANCELLED",
		5: "TASK_STATUS_EXPIRED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_OPEN":        1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_CANCELLED":   4,
		"TASK_STATUS_EXPIRED":     5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_task_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_PB_task_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SchoolId    int64                  `protobuf:"varint,2,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	UserId      int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 发布者
	ClaimantId  int64                  `protobuf:"varint,4,opt,name=claimant_id,json=claimantId,proto3" json:"claimant_id,omitempty"` // 接单者（0=未接单）
	TaskType    TaskType               `protobuf:"varint,5,opt,name=task_type,json=taskType,proto3,enum=pb.TaskType" json:"task_type,omitempty"`
	Title       string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Location    string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	RewardDesc  string                 `protobuf:"bytes,9,opt,name=reward_desc,json=rewardDesc,proto3" json:"reward_desc,omitempty"`
	// 联系方式与留言（接单前隐藏，仅相关方可见）
	Contact         string     `protobuf:"bytes,10,opt,name=contact,proto3" json:"contact,omitempty"`                                        // 发布者联系方式
	Note            string     `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`                                              // 发布者留言
	ClaimantContact string     `protobuf:"bytes,12,opt,name=claimant_contact,json=claimantContact,proto3" json:"claimant_contact,omitempty"` // 接单者联系方式
	ClaimantMsg     string     `protobuf:"bytes,13,opt,name=claimant_msg,json=claimantMsg,proto3" json:"claimant_msg,omitempty"`             // 接单者留言
	Status          TaskStatus `protobuf:"varint,14,opt,name=status,proto3,enum=pb.TaskStatus" json:"status,omitempty"`
	ExpiredAt       int64      `protobuf:"varint,15,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // 过期时间（Unix 时间戳）
	CreatedAt       int64      `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64      `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 冗余信息（跨服务填充）
	PublisherNickname string `protobuf:"bytes,18,opt,name=publisher_nickname,json=publisherNickname,proto3" json:"publisher_nickname,omitempty"`
	PublisherAvatar   string `protobuf:"bytes,19,opt,name=publisher_avatar,json=publisherAvatar,proto3" json:"publisher_avatar,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_PB_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *Task) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Task) GetClaimantId() int64 {
	if x != nil {
		return x.ClaimantId
	}
	return 0
}

func (x *Task) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Task) GetRewardDesc() string {
	if x != nil {
		return x.RewardDesc
	}
	return ""
}

func (x *Task) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Task) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Task) GetClaimantContact() string {
	if x != nil {
		return x.ClaimantContact
	}
	return ""
}

func (x *Task) GetClaimantMsg() string {
	if x != nil {
		return x.ClaimantMsg
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Task) GetPublisherNickname() string {
	if x != nil {
		return x.PublisherNickname
	}
	return ""
}

func (x *Task) GetPublisherAvatar() string {
	if x != nil {
		return x.PublisherAvatar
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskType      TaskType               `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=pb.TaskType" json:"task_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	RewardDesc    string                 `protobuf:"bytes,7,opt,name=reward_desc,json=rewardDesc,proto3" json:"reward_desc,omitempty"`
	Contact       string                 `protobuf:"bytes,8,opt,name=contact,proto3" json:"contact,omitempty"`                        // 发布者联系方式
	Note          string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`                              // 发布者留言
	ExpiredAt     int64                  `protobuf:"varint,10,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // 过期时间（可选，默认 24h）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_PB_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *CreateTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTaskRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateTaskRequest) GetRewardDesc() string {
	if x != nil {
		return x.RewardDesc
	}
	return ""
}

func (x *CreateTaskRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *CreateTaskRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateTaskRequest) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_PB_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateTaskResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTaskResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 当前请求用户（用于判断是否展示联系方式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_PB_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *GetTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TaskType      TaskType               `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=pb.TaskType" json:"task_type,omitempty"` // 筛选（可选）
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=pb.TaskStatus" json:"status,omitempty"`                   // 筛选（可选，默认 open）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_PB_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *ListTasksRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_PB_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListTasksResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	RewardDesc    string                 `protobuf:"bytes,7,opt,name=reward_desc,json=rewardDesc,proto3" json:"reward_desc,omitempty"`
	Contact       string                 `protobuf:"bytes,8,opt,name=contact,proto3" json:"contact,omitempty"`
	Note          string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_PB_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTaskRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *UpdateTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *UpdateTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateTaskRequest) GetRewardDesc() string {
	if x != nil {
		return x.RewardDesc
	}
	return ""
}

func (x *UpdateTaskRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *UpdateTaskRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_PB_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTaskRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *DeleteTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *DeleteTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClaimTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 接单者
	Contact       string                 `protobuf:"bytes,4,opt,name=contact,proto3" json:"contact,omitempty"`              // 接单者联系方式（必填）
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`              // 接单者留言（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRequest) Reset() {
	*x = ClaimTaskRequest{}
	mi := &file_PB_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRequest) ProtoMessage() {}

func (x *ClaimTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimTaskRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *ClaimTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ClaimTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimTaskRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *ClaimTaskRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 接单者
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_PB_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteTaskRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *CompleteTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CompleteTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_PB_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_PB_task_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTaskRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *CancelTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CancelTaskRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_PB_task_proto protoreflect.FileDescriptor

const file_PB_task_proto_rawDesc = "" +
	"\n" +
	"\rPB/task.proto\x12\x02pb\x1a\x0fPB/common.proto\"\xe8\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tschool_id\x18\x02 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vclaimant_id\x18\x04 \x01(\x03R\n" +
	"claimantId\x12)\n" +
	"\ttask_type\x18\x05 \x01(\x0e2\f.pb.TaskTypeR\btaskType\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1f\n" +
	"\vreward_desc\x18\t \x01(\tR\n" +
	"rewardDesc\x12\x18\n" +
	"\acontact\x18\n" +
	" \x01(\tR\acontact\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x12)\n" +
	"\x10claimant_contact\x18\f \x01(\tR\x0fclaimantContact\x12!\n" +
	"\fclaimant_msg\x18\r \x01(\tR\vclaimantMsg\x12&\n" +
	"\x06status\x18\x0e \x01(\x0e2\x0e.pb.TaskStatusR\x06status\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x0f \x01(\x03R\texpiredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\x03R\tupdatedAt\x12-\n" +
	"\x12publisher_nickname\x18\x12 \x01(\tR\x11publisherNickname\x12)\n" +
	"\x10publisher_avatar\x18\x13 \x01(\tR\x0fpublisherAvatar\"\xb6\x02\n" +
	"\x11CreateTaskRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12)\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\f.pb.TaskTypeR\btaskType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1f\n" +
	"\vreward_desc\x18\a \x01(\tR\n" +
	"rewardDesc\x12\x18\n" +
	"\acontact\x18\b \x01(\tR\acontact\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\x12\x1d\n" +
	"\n" +
	"expired_at\x18\n" +
	" \x01(\x03R\texpiredAt\"d\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"_\n" +
	"\x0eGetTaskRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"\xb7\x01\n" +
	"\x10ListTasksRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12)\n" +
	"\ttask_type\x18\x04 \x01(\x0e2\f.pb.TaskTypeR\btaskType\x12&\n" +
	"\x06status\x18\x05 \x01(\x0e2\x0e.pb.TaskStatusR\x06status\"o\n" +
	"\x11ListTasksResponse\x12\x1e\n" +
	"\x05tasks\x18\x01 \x03(\v2\b.pb.TaskR\x05tasks\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"\x85\x02\n" +
	"\x11UpdateTaskRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12\x1f\n" +
	"\vreward_desc\x18\a \x01(\tR\n" +
	"rewardDesc\x12\x18\n" +
	"\acontact\x18\b \x01(\tR\acontact\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\"b\n" +
	"\x11DeleteTaskRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"\x95\x01\n" +
	"\x10ClaimTaskRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontact\x18\x04 \x01(\tR\acontact\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"d\n" +
	"\x13CompleteTaskRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"b\n" +
	"\x11CancelTaskRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId*j\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_TYPE_DELIVERY\x10\x01\x12\x15\n" +
	"\x11TASK_TYPE_CARPOOL\x10\x02\x12\x14\n" +
	"\x10TASK_TYPE_BOUNTY\x10\x03*\xab\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_STATUS_OPEN\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x04\x12\x17\n" +
	"\x13TASK_STATUS_EXPIRED\x10\x052\xba\x03\n" +
	"\vTaskService\x12;\n" +
	"\n" +
	"CreateTask\x12\x15.pb.CreateTaskRequest\x1a\x16.pb.CreateTaskResponse\x12'\n" +
	"\aGetTask\x12\x12.pb.GetTaskRequest\x1a\b.pb.Task\x128\n" +
	"\tListTasks\x12\x14.pb.ListTasksRequest\x1a\x15.pb.ListTasksResponse\x12-\n" +
	"\n" +
	"UpdateTask\x12\x15.pb.UpdateTaskRequest\x1a\b.pb.Task\x125\n" +
	"\n" +
	"DeleteTask\x12\x15.pb.DeleteTaskRequest\x1a\x10.pb.BaseResponse\x123\n" +
	"\tClaimTask\x12\x14.pb.ClaimTaskRequest\x1a\x10.pb.BaseResponse\x129\n" +
	"\fCompleteTask\x12\x17.pb.CompleteTaskRequest\x1a\x10.pb.BaseResponse\x125\n" +
	"\n" +
	"CancelTask\x12\x15.pb.CancelTaskRequest\x1a\x10.pb.BaseResponseB\n" +
	"Z\b/task_pbb\x06proto3"

var (
	file_PB_task_proto_rawDescOnce sync.Once
	file_PB_task_proto_rawDescData []byte
)

func file_PB_task_proto_rawDescGZIP() []byte {
	file_PB_task_proto_rawDescOnce.Do(func() {
		file_PB_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_task_proto_rawDesc), len(file_PB_task_proto_rawDesc)))
	})
	return file_PB_task_proto_rawDescData
}

var file_PB_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_PB_task_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_PB_task_proto_goTypes = []any{
	(TaskType)(0),                  // 0: pb.TaskType
	(TaskStatus)(0),                // 1: pb.TaskStatus
	(*Task)(nil),                   // 2: pb.Task
	(*CreateTaskRequest)(nil),      // 3: pb.CreateTaskRequest
	(*CreateTaskResponse)(nil),     // 4: pb.CreateTaskResponse
	(*GetTaskRequest)(nil),         // 5: pb.GetTaskRequest
	(*ListTasksRequest)(nil),       // 6: pb.ListTasksRequest
	(*ListTasksResponse)(nil),      // 7: pb.ListTasksResponse
	(*UpdateTaskRequest)(nil),      // 8: pb.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),      // 9: pb.DeleteTaskRequest
	(*ClaimTaskRequest)(nil),       // 10: pb.ClaimTaskRequest
	(*CompleteTaskRequest)(nil),    // 11: pb.CompleteTaskRequest
	(*CancelTaskRequest)(nil),      // 12: pb.CancelTaskRequest
	(*common_pb.BaseResponse)(nil), // 13: pb.BaseResponse
}
var file_PB_task_proto_depIdxs = []int32{
	0,  // 0: pb.Task.task_type:type_name -> pb.TaskType
	1,  // 1: pb.Task.status:type_name -> pb.TaskStatus
	0,  // 2: pb.CreateTaskRequest.task_type:type_name -> pb.TaskType
	0,  // 3: pb.ListTasksRequest.task_type:type_name -> pb.TaskType
	1,  // 4: pb.ListTasksRequest.status:type_name -> pb.TaskStatus
	2,  // 5: pb.ListTasksResponse.tasks:type_name -> pb.Task
	3,  // 6: pb.TaskService.CreateTask:input_type -> pb.CreateTaskRequest
	5,  // 7: pb.TaskService.GetTask:input_type -> pb.GetTaskRequest
	6,  // 8: pb.TaskService.ListTasks:input_type -> pb.ListTasksRequest
	8,  // 9: pb.TaskService.UpdateTask:input_type -> pb.UpdateTaskRequest
	9,  // 10: pb.TaskService.DeleteTask:input_type -> pb.DeleteTaskRequest
	10, // 11: pb.TaskService.ClaimTask:input_type -> pb.ClaimTaskRequest
	11, // 12: pb.TaskService.CompleteTask:input_type -> pb.CompleteTaskRequest
	12, // 13: pb.TaskService.CancelTask:input_type -> pb.CancelTaskRequest
	4,  // 14: pb.TaskService.CreateTask:output_type -> pb.CreateTaskResponse
	2,  // 15: pb.TaskService.GetTask:output_type -> pb.Task
	7,  // 16: pb.TaskService.ListTasks:output_type -> pb.ListTasksResponse
	2,  // 17: pb.TaskService.UpdateTask:output_type -> pb.Task
	13, // 18: pb.TaskService.DeleteTask:output_type -> pb.BaseResponse
	13, // 19: pb.TaskService.ClaimTask:output_type -> pb.BaseResponse
	13, // 20: pb.TaskService.CompleteTask:output_type -> pb.BaseResponse
	13, // 21: pb.TaskService.CancelTask:output_type -> pb.BaseResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_PB_task_proto_init() }
func file_PB_task_proto_init() {
	if File_PB_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_task_proto_rawDesc), len(file_PB_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PB_task_proto_goTypes,
		DependencyIndexes: file_PB_task_proto_depIdxs,
		EnumInfos:         file_PB_task_proto_enumTypes,
		MessageInfos:      file_PB_task_proto_msgTypes,
	}.Build()
	File_PB_task_proto = out.File
	file_PB_task_proto_goTypes = nil
	file_PB_task_proto_depIdxs = nil
}
