// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: PB/ai_moderation.proto

package ai_moderation_pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Result AI 决策结果
type ModerateTextResponse_Result int32

const (
	ModerateTextResponse_PASS   ModerateTextResponse_Result = 0 // 内容正常，放行
	ModerateTextResponse_REVIEW ModerateTextResponse_Result = 1 // AI 不确定，进人工池
	ModerateTextResponse_BLOCK  ModerateTextResponse_Result = 2 // 内容违规，拦截
)

// Enum value maps for ModerateTextResponse_Result.
var (
	ModerateTextResponse_Result_name = map[int32]string{
		0: "PASS",
		1: "REVIEW",
		2: "BLOCK",
	}
	ModerateTextResponse_Result_value = map[string]int32{
		"PASS":   0,
		"REVIEW": 1,
		"BLOCK":  2,
	}
)

func (x ModerateTextResponse_Result) Enum() *ModerateTextResponse_Result {
	p := new(ModerateTextResponse_Result)
	*p = x
	return p
}

func (x ModerateTextResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModerateTextResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_ai_moderation_proto_enumTypes[0].Descriptor()
}

func (ModerateTextResponse_Result) Type() protoreflect.EnumType {
	return &file_PB_ai_moderation_proto_enumTypes[0]
}

func (x ModerateTextResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModerateTextResponse_Result.Descriptor instead.
func (ModerateTextResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_PB_ai_moderation_proto_rawDescGZIP(), []int{1, 0}
}

// Status 调用状态（区分同步/降级/异步）
type ModerateTextResponse_Status int32

const (
	ModerateTextResponse_SYNCED   ModerateTextResponse_Status = 0 // 正常同步调用
	ModerateTextResponse_DEGRADED ModerateTextResponse_Status = 1 // AI 服务降级（不可用/超时/熔断）
	ModerateTextResponse_ASYNC    ModerateTextResponse_Status = 2 // 异步补判调用
)

// Enum value maps for ModerateTextResponse_Status.
var (
	ModerateTextResponse_Status_name = map[int32]string{
		0: "SYNCED",
		1: "DEGRADED",
		2: "ASYNC",
	}
	ModerateTextResponse_Status_value = map[string]int32{
		"SYNCED":   0,
		"DEGRADED": 1,
		"ASYNC":    2,
	}
)

func (x ModerateTextResponse_Status) Enum() *ModerateTextResponse_Status {
	p := new(ModerateTextResponse_Status)
	*p = x
	return p
}

func (x ModerateTextResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModerateTextResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_ai_moderation_proto_enumTypes[1].Descriptor()
}

func (ModerateTextResponse_Status) Type() protoreflect.EnumType {
	return &file_PB_ai_moderation_proto_enumTypes[1]
}

func (x ModerateTextResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModerateTextResponse_Status.Descriptor instead.
func (ModerateTextResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_PB_ai_moderation_proto_rawDescGZIP(), []int{1, 1}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 1
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "SERVING",
		1: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"SERVING":     0,
		"NOT_SERVING": 1,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_PB_ai_moderation_proto_enumTypes[2].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_PB_ai_moderation_proto_enumTypes[2]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_PB_ai_moderation_proto_rawDescGZIP(), []int{2, 0}
}

type ModerateTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                      // 待审核文本（≤ 1000 字，超过会在 ai-moderation 侧截断到 512 token）
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 调用方传入的 trace_id（用于 Jaeger 关联）
	PostId        int64                  `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`   // 帖子 ID（用于 ai_audit_logs 审计）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateTextRequest) Reset() {
	*x = ModerateTextRequest{}
	mi := &file_PB_ai_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateTextRequest) ProtoMessage() {}

func (x *ModerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ai_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateTextRequest.ProtoReflect.Descriptor instead.
func (*ModerateTextRequest) Descriptor() ([]byte, []int) {
	return file_PB_ai_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *ModerateTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ModerateTextRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ModerateTextRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type ModerateTextResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Result        ModerateTextResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=pb.ModerateTextResponse_Result" json:"result,omitempty"`
	Status        ModerateTextResponse_Status `protobuf:"varint,7,opt,name=status,proto3,enum=pb.ModerateTextResponse_Status" json:"status,omitempty"`
	Confidence    float32                     `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0 - 1.0
	Categories    []string                    `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`   // 命中类别（如 ["涉政", "广告引流"]）
	LatencyMs     int64                       `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ModelVersion  string                      `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	FallbackUsed  bool                        `protobuf:"varint,6,opt,name=fallback_used,json=fallbackUsed,proto3" json:"fallback_used,omitempty"` // true 表示走了降级逻辑（mock 或 fallback）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModerateTextResponse) Reset() {
	*x = ModerateTextResponse{}
	mi := &file_PB_ai_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerateTextResponse) ProtoMessage() {}

func (x *ModerateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ai_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerateTextResponse.ProtoReflect.Descriptor instead.
func (*ModerateTextResponse) Descriptor() ([]byte, []int) {
	return file_PB_ai_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *ModerateTextResponse) GetResult() ModerateTextResponse_Result {
	if x != nil {
		return x.Result
	}
	return ModerateTextResponse_PASS
}

func (x *ModerateTextResponse) GetStatus() ModerateTextResponse_Status {
	if x != nil {
		return x.Status
	}
	return ModerateTextResponse_SYNCED
}

func (x *ModerateTextResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ModerateTextResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ModerateTextResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ModerateTextResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ModerateTextResponse) GetFallbackUsed() bool {
	if x != nil {
		return x.FallbackUsed
	}
	return false
}

type HealthCheckResponse struct {
	state              protoimpl.MessageState            `protogen:"open.v1"`
	Status             HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=pb.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	ModelLoaded        bool                              `protobuf:"varint,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`                        // ONNX 模型是否加载成功
	ModelVersion       string                            `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`                      // 当前模型版本
	ModelLoadTimestamp int64                             `protobuf:"varint,4,opt,name=model_load_timestamp,json=modelLoadTimestamp,proto3" json:"model_load_timestamp,omitempty"` // 模型加载时间（Unix 秒）
	Mode               string                            `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`                                                          // "mock" 或 "onnxruntime"
	IntraOpThreads     int32                             `protobuf:"varint,6,opt,name=intra_op_threads,json=intraOpThreads,proto3" json:"intra_op_threads,omitempty"`             // ONNX 内部线程数
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_PB_ai_moderation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_ai_moderation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_PB_ai_moderation_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_SERVING
}

func (x *HealthCheckResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *HealthCheckResponse) GetModelLoadTimestamp() int64 {
	if x != nil {
		return x.ModelLoadTimestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *HealthCheckResponse) GetIntraOpThreads() int32 {
	if x != nil {
		return x.IntraOpThreads
	}
	return 0
}

var File_PB_ai_moderation_proto protoreflect.FileDescriptor

const file_PB_ai_moderation_proto_rawDesc = "" +
	"\n" +
	"\x16PB/ai_moderation.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"]\n" +
	"\x13ModerateTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x03R\x06postId\"\x8b\x03\n" +
	"\x14ModerateTextResponse\x127\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1f.pb.ModerateTextResponse.ResultR\x06result\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.pb.ModerateTextResponse.StatusR\x06status\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12#\n" +
	"\rmodel_version\x18\x05 \x01(\tR\fmodelVersion\x12#\n" +
	"\rfallback_used\x18\x06 \x01(\bR\ffallbackUsed\")\n" +
	"\x06Result\x12\b\n" +
	"\x04PASS\x10\x00\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x01\x12\t\n" +
	"\x05BLOCK\x10\x02\"-\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06SYNCED\x10\x00\x12\f\n" +
	"\bDEGRADED\x10\x01\x12\t\n" +
	"\x05ASYNC\x10\x02\"\xbb\x02\n" +
	"\x13HealthCheckResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.pb.HealthCheckResponse.ServingStatusR\x06status\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\bR\vmodelLoaded\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x120\n" +
	"\x14model_load_timestamp\x18\x04 \x01(\x03R\x12modelLoadTimestamp\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12(\n" +
	"\x10intra_op_threads\x18\x06 \x01(\x05R\x0eintraOpThreads\"-\n" +
	"\rServingStatus\x12\v\n" +
	"\aSERVING\x10\x00\x12\x0f\n" +
	"\vNOT_SERVING\x10\x012\x98\x01\n" +
	"\x13AIModerationService\x12A\n" +
	"\fModerateText\x12\x17.pb.ModerateTextRequest\x1a\x18.pb.ModerateTextResponse\x12>\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x17.pb.HealthCheckResponseB0Z.go_projects/praProject1/PB/pb/ai_moderation_pbb\x06proto3"

var (
	file_PB_ai_moderation_proto_rawDescOnce sync.Once
	file_PB_ai_moderation_proto_rawDescData []byte
)

func file_PB_ai_moderation_proto_rawDescGZIP() []byte {
	file_PB_ai_moderation_proto_rawDescOnce.Do(func() {
		file_PB_ai_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_ai_moderation_proto_rawDesc), len(file_PB_ai_moderation_proto_rawDesc)))
	})
	return file_PB_ai_moderation_proto_rawDescData
}

var file_PB_ai_moderation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_PB_ai_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PB_ai_moderation_proto_goTypes = []any{
	(ModerateTextResponse_Result)(0),       // 0: pb.ModerateTextResponse.Result
	(ModerateTextResponse_Status)(0),       // 1: pb.ModerateTextResponse.Status
	(HealthCheckResponse_ServingStatus)(0), // 2: pb.HealthCheckResponse.ServingStatus
	(*ModerateTextRequest)(nil),            // 3: pb.ModerateTextRequest
	(*ModerateTextResponse)(nil),           // 4: pb.ModerateTextResponse
	(*HealthCheckResponse)(nil),            // 5: pb.HealthCheckResponse
	(*empty.Empty)(nil),                    // 6: google.protobuf.Empty
}
var file_PB_ai_moderation_proto_depIdxs = []int32{
	0, // 0: pb.ModerateTextResponse.result:type_name -> pb.ModerateTextResponse.Result
	1, // 1: pb.ModerateTextResponse.status:type_name -> pb.ModerateTextResponse.Status
	2, // 2: pb.HealthCheckResponse.status:type_name -> pb.HealthCheckResponse.ServingStatus
	3, // 3: pb.AIModerationService.ModerateText:input_type -> pb.ModerateTextRequest
	6, // 4: pb.AIModerationService.HealthCheck:input_type -> google.protobuf.Empty
	4, // 5: pb.AIModerationService.ModerateText:output_type -> pb.ModerateTextResponse
	5, // 6: pb.AIModerationService.HealthCheck:output_type -> pb.HealthCheckResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_PB_ai_moderation_proto_init() }
func file_PB_ai_moderation_proto_init() {
	if File_PB_ai_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_ai_moderation_proto_rawDesc), len(file_PB_ai_moderation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PB_ai_moderation_proto_goTypes,
		DependencyIndexes: file_PB_ai_moderation_proto_depIdxs,
		EnumInfos:         file_PB_ai_moderation_proto_enumTypes,
		MessageInfos:      file_PB_ai_moderation_proto_msgTypes,
	}.Build()
	File_PB_ai_moderation_proto = out.File
	file_PB_ai_moderation_proto_goTypes = nil
	file_PB_ai_moderation_proto_depIdxs = nil
}
