// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: PB/ai_moderation.proto

package ai_moderation_pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIModerationService_ModerateText_FullMethodName = "/pb.AIModerationService/ModerateText"
	AIModerationService_HealthCheck_FullMethodName  = "/pb.AIModerationService/HealthCheck"
)

// AIModerationServiceClient is the client API for AIModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIModerationService 提供本地 AI 内容审核能力（第 8 个微服务）。
//
// 设计要点：
//   - 同步单条审核：ModerateText（800ms 超时）
//   - 健康检查：HealthCheck（含模型加载状态）
//   - Result 枚举：PASS / REVIEW / BLOCK（与 internal/ai_moderation/model.go Result 一致）
//   - Status 枚举：SYNCED / DEGRADED / ASYNC（区分同步调用/降级/异步补判）
//
// 关联：
//   - PRD docs/ai-moderation-content-service-v3.0-prd.md
//   - Epic #89, Issue #91
type AIModerationServiceClient interface {
	// 同步单条文本审核（Content Service.CreatePost 路径同步调用）
	ModerateText(ctx context.Context, in *ModerateTextRequest, opts ...grpc.CallOption) (*ModerateTextResponse, error)
	// 健康检查（grpc_health_v1 标准接口之外，额外提供业务级 health 检查）
	HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aIModerationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIModerationServiceClient(cc grpc.ClientConnInterface) AIModerationServiceClient {
	return &aIModerationServiceClient{cc}
}

func (c *aIModerationServiceClient) ModerateText(ctx context.Context, in *ModerateTextRequest, opts ...grpc.CallOption) (*ModerateTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerateTextResponse)
	err := c.cc.Invoke(ctx, AIModerationService_ModerateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIModerationServiceClient) HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AIModerationService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIModerationServiceServer is the server API for AIModerationService service.
// All implementations must embed UnimplementedAIModerationServiceServer
// for forward compatibility.
//
// AIModerationService 提供本地 AI 内容审核能力（第 8 个微服务）。
//
// 设计要点：
//   - 同步单条审核：ModerateText（800ms 超时）
//   - 健康检查：HealthCheck（含模型加载状态）
//   - Result 枚举：PASS / REVIEW / BLOCK（与 internal/ai_moderation/model.go Result 一致）
//   - Status 枚举：SYNCED / DEGRADED / ASYNC（区分同步调用/降级/异步补判）
//
// 关联：
//   - PRD docs/ai-moderation-content-service-v3.0-prd.md
//   - Epic #89, Issue #91
type AIModerationServiceServer interface {
	// 同步单条文本审核（Content Service.CreatePost 路径同步调用）
	ModerateText(context.Context, *ModerateTextRequest) (*ModerateTextResponse, error)
	// 健康检查（grpc_health_v1 标准接口之外，额外提供业务级 health 检查）
	HealthCheck(context.Context, *empty.Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAIModerationServiceServer()
}

// UnimplementedAIModerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIModerationServiceServer struct{}

func (UnimplementedAIModerationServiceServer) ModerateText(context.Context, *ModerateTextRequest) (*ModerateTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateText not implemented")
}
func (UnimplementedAIModerationServiceServer) HealthCheck(context.Context, *empty.Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAIModerationServiceServer) mustEmbedUnimplementedAIModerationServiceServer() {}
func (UnimplementedAIModerationServiceServer) testEmbeddedByValue()                             {}

// UnsafeAIModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIModerationServiceServer will
// result in compilation errors.
type UnsafeAIModerationServiceServer interface {
	mustEmbedUnimplementedAIModerationServiceServer()
}

func RegisterAIModerationServiceServer(s grpc.ServiceRegistrar, srv AIModerationServiceServer) {
	// If the following call panics, it indicates UnimplementedAIModerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIModerationService_ServiceDesc, srv)
}

func _AIModerationService_ModerateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModerationServiceServer).ModerateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModerationService_ModerateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModerationServiceServer).ModerateText(ctx, req.(*ModerateTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIModerationService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIModerationServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIModerationService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIModerationServiceServer).HealthCheck(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AIModerationService_ServiceDesc is the grpc.ServiceDesc for AIModerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIModerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AIModerationService",
	HandlerType: (*AIModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModerateText",
			Handler:    _AIModerationService_ModerateText_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AIModerationService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PB/ai_moderation.proto",
}
