// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: PB/user.proto

package user_pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	common_pb "go_projects/praProject1/PB/pb/common_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WxLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsCode        string                 `protobuf:"bytes,1,opt,name=js_code,json=jsCode,proto3" json:"js_code,omitempty"` // 微信 wx.login() 获取的 code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginRequest) Reset() {
	*x = WxLoginRequest{}
	mi := &file_PB_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginRequest) ProtoMessage() {}

func (x *WxLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginRequest.ProtoReflect.Descriptor instead.
func (*WxLoginRequest) Descriptor() ([]byte, []int) {
	return file_PB_user_proto_rawDescGZIP(), []int{0}
}

func (x *WxLoginRequest) GetJsCode() string {
	if x != nil {
		return x.JsCode
	}
	return ""
}

type WxLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	IsBoundCampus bool                   `protobuf:"varint,2,opt,name=is_bound_campus,json=isBoundCampus,proto3" json:"is_bound_campus,omitempty"` // 标记是否已绑定学校，未绑定则前端强制跳转绑定页
	SchoolId      int64                  `protobuf:"varint,3,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`                  // 已绑定的学校ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginResponse) Reset() {
	*x = WxLoginResponse{}
	mi := &file_PB_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginResponse) ProtoMessage() {}

func (x *WxLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginResponse.ProtoReflect.Descriptor instead.
func (*WxLoginResponse) Descriptor() ([]byte, []int) {
	return file_PB_user_proto_rawDescGZIP(), []int{1}
}

func (x *WxLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *WxLoginResponse) GetIsBoundCampus() bool {
	if x != nil {
		return x.IsBoundCampus
	}
	return false
}

func (x *WxLoginResponse) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

type BindCampusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolName    string                 `protobuf:"bytes,1,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"` // 选择的学校名称,根据传入的名称搜索对应的id绑定到用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindCampusRequest) Reset() {
	*x = BindCampusRequest{}
	mi := &file_PB_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindCampusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindCampusRequest) ProtoMessage() {}

func (x *BindCampusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindCampusRequest.ProtoReflect.Descriptor instead.
func (*BindCampusRequest) Descriptor() ([]byte, []int) {
	return file_PB_user_proto_rawDescGZIP(), []int{2}
}

func (x *BindCampusRequest) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_PB_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_PB_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	SchoolId      int64                  `protobuf:"varint,4,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`      // 【关键】所属学校ID（修复：int64 → uint64）
	SchoolName    string                 `protobuf:"bytes,5,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"` // 冗余学校名称，减少网关聚合调用
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`                               // student, admin, super_admin
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_PB_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PB_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_PB_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *UserInfo) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 新昵称（可选）
	AvatarUrl     string                 `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 新头像URL（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_PB_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_PB_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserInfoRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type SchoolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolInfo) Reset() {
	*x = SchoolInfo{}
	mi := &file_PB_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolInfo) ProtoMessage() {}

func (x *SchoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_PB_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolInfo.ProtoReflect.Descriptor instead.
func (*SchoolInfo) Descriptor() ([]byte, []int) {
	return file_PB_user_proto_rawDescGZIP(), []int{6}
}

func (x *SchoolInfo) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *SchoolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchoolInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

var File_PB_user_proto protoreflect.FileDescriptor

const file_PB_user_proto_rawDesc = "" +
	"\n" +
	"\rPB/user.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fPB/common.proto\")\n" +
	"\x0eWxLoginRequest\x12\x17\n" +
	"\ajs_code\x18\x01 \x01(\tR\x06jsCode\"y\n" +
	"\x0fWxLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12&\n" +
	"\x0fis_bound_campus\x18\x02 \x01(\bR\risBoundCampus\x12\x1b\n" +
	"\tschool_id\x18\x03 \x01(\x03R\bschoolId\"4\n" +
	"\x11BindCampusRequest\x12\x1f\n" +
	"\vschool_name\x18\x01 \x01(\tR\n" +
	"schoolName\"0\n" +
	"\x15GetCurrentUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xeb\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tschool_id\x18\x04 \x01(\x03R\bschoolId\x12\x1f\n" +
	"\vschool_name\x18\x05 \x01(\tR\n" +
	"schoolName\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x15UpdateUserInfoRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tR\tavatarUrl\"Y\n" +
	"\n" +
	"SchoolInfo\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince2\xf2\x01\n" +
	"\vUserService\x122\n" +
	"\aWxLogin\x12\x12.pb.WxLoginRequest\x1a\x13.pb.WxLoginResponse\x125\n" +
	"\n" +
	"BindCampus\x12\x15.pb.BindCampusRequest\x1a\x10.pb.BaseResponse\x129\n" +
	"\x0eGetCurrentUser\x12\x19.pb.GetCurrentUserRequest\x1a\f.pb.UserInfo\x12=\n" +
	"\x0eUpdateUserInfo\x12\x19.pb.UpdateUserInfoRequest\x1a\x10.pb.BaseResponseB'Z%go_projects/praProject1/PB/pb/user_pbb\x06proto3"

var (
	file_PB_user_proto_rawDescOnce sync.Once
	file_PB_user_proto_rawDescData []byte
)

func file_PB_user_proto_rawDescGZIP() []byte {
	file_PB_user_proto_rawDescOnce.Do(func() {
		file_PB_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_user_proto_rawDesc), len(file_PB_user_proto_rawDesc)))
	})
	return file_PB_user_proto_rawDescData
}

var file_PB_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_PB_user_proto_goTypes = []any{
	(*WxLoginRequest)(nil),         // 0: pb.WxLoginRequest
	(*WxLoginResponse)(nil),        // 1: pb.WxLoginResponse
	(*BindCampusRequest)(nil),      // 2: pb.BindCampusRequest
	(*GetCurrentUserRequest)(nil),  // 3: pb.GetCurrentUserRequest
	(*UserInfo)(nil),               // 4: pb.UserInfo
	(*UpdateUserInfoRequest)(nil),  // 5: pb.UpdateUserInfoRequest
	(*SchoolInfo)(nil),             // 6: pb.SchoolInfo
	(*timestamp.Timestamp)(nil),    // 7: google.protobuf.Timestamp
	(*common_pb.BaseResponse)(nil), // 8: pb.BaseResponse
}
var file_PB_user_proto_depIdxs = []int32{
	7, // 0: pb.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: pb.UserService.WxLogin:input_type -> pb.WxLoginRequest
	2, // 2: pb.UserService.BindCampus:input_type -> pb.BindCampusRequest
	3, // 3: pb.UserService.GetCurrentUser:input_type -> pb.GetCurrentUserRequest
	5, // 4: pb.UserService.UpdateUserInfo:input_type -> pb.UpdateUserInfoRequest
	1, // 5: pb.UserService.WxLogin:output_type -> pb.WxLoginResponse
	8, // 6: pb.UserService.BindCampus:output_type -> pb.BaseResponse
	4, // 7: pb.UserService.GetCurrentUser:output_type -> pb.UserInfo
	8, // 8: pb.UserService.UpdateUserInfo:output_type -> pb.BaseResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PB_user_proto_init() }
func file_PB_user_proto_init() {
	if File_PB_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_user_proto_rawDesc), len(file_PB_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PB_user_proto_goTypes,
		DependencyIndexes: file_PB_user_proto_depIdxs,
		MessageInfos:      file_PB_user_proto_msgTypes,
	}.Build()
	File_PB_user_proto = out.File
	file_PB_user_proto_goTypes = nil
	file_PB_user_proto_depIdxs = nil
}
