// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: PB/message.proto

package message_pb

import (
	common_pb "go_projects/praProject1/PB/pb/common_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                  // liked / published / review_result / taken_down / replied
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                                // 通知标题（含快照）
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                            // 通知正文/预览
	FromUserId    int64                  `protobuf:"varint,5,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 触发者 user_id（可选）
	RefType       string                 `protobuf:"bytes,6,opt,name=ref_type,json=refType,proto3" json:"ref_type,omitempty"`             // 关联类型：post / comment
	RefId         int64                  `protobuf:"varint,7,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`                  // 关联 ID
	IsRead        bool                   `protobuf:"varint,8,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`               // 是否已读
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // 创建时间（Unix 时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_PB_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *Notification) GetRefType() string {
	if x != nil {
		return x.RefType
	}
	return ""
}

func (x *Notification) GetRefId() int64 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`                      // 游标（Base64 编码）
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量，上限 50
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                          // 按类型筛选（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_PB_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *ListNotificationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListNotificationsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotificationsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,2,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_PB_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ListNotificationsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListNotificationsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type UnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountRequest) Reset() {
	*x = UnreadCountRequest{}
	mi := &file_PB_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountRequest) ProtoMessage() {}

func (x *UnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountRequest.ProtoReflect.Descriptor instead.
func (*UnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{3}
}

func (x *UnreadCountRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *UnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnreadCountResponse) Reset() {
	*x = UnreadCountResponse{}
	mi := &file_PB_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnreadCountResponse) ProtoMessage() {}

func (x *UnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnreadCountResponse.ProtoReflect.Descriptor instead.
func (*UnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{4}
}

func (x *UnreadCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarkReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 通知 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_PB_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{5}
}

func (x *MarkReadRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarkReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MarkAllReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchoolId      int64                  `protobuf:"varint,1,opt,name=school_id,json=schoolId,proto3" json:"school_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadRequest) Reset() {
	*x = MarkAllReadRequest{}
	mi := &file_PB_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadRequest) ProtoMessage() {}

func (x *MarkAllReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllReadRequest) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{6}
}

func (x *MarkAllReadRequest) GetSchoolId() int64 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *MarkAllReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 通知 ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_PB_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_PB_message_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNotificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteNotificationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_PB_message_proto protoreflect.FileDescriptor

const file_PB_message_proto_rawDesc = "" +
	"\n" +
	"\x10PB/message.proto\x12\x02pb\x1a\x0fPB/common.proto\"\xee\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\ffrom_user_id\x18\x05 \x01(\x03R\n" +
	"fromUserId\x12\x19\n" +
	"\bref_type\x18\x06 \x01(\tR\arefType\x12\x15\n" +
	"\x06ref_id\x18\a \x01(\x03R\x05refId\x12\x17\n" +
	"\ais_read\x18\b \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\x99\x01\n" +
	"\x18ListNotificationsRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\xb2\x01\n" +
	"\x19ListNotificationsResponse\x126\n" +
	"\rnotifications\x18\x01 \x03(\v2\x10.pb.NotificationR\rnotifications\x12!\n" +
	"\funread_count\x18\x02 \x01(\x03R\vunreadCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\"J\n" +
	"\x12UnreadCountRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"+\n" +
	"\x13UnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\":\n" +
	"\x0fMarkReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"J\n" +
	"\x12MarkAllReadRequest\x12\x1b\n" +
	"\tschool_id\x18\x01 \x01(\x03R\bschoolId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"D\n" +
	"\x19DeleteNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId2\xd5\x02\n" +
	"\x0eMessageService\x12P\n" +
	"\x11ListNotifications\x12\x1c.pb.ListNotificationsRequest\x1a\x1d.pb.ListNotificationsResponse\x12>\n" +
	"\vUnreadCount\x12\x16.pb.UnreadCountRequest\x1a\x17.pb.UnreadCountResponse\x121\n" +
	"\bMarkRead\x12\x13.pb.MarkReadRequest\x1a\x10.pb.BaseResponse\x127\n" +
	"\vMarkAllRead\x12\x16.pb.MarkAllReadRequest\x1a\x10.pb.BaseResponse\x12E\n" +
	"\x12DeleteNotification\x12\x1d.pb.DeleteNotificationRequest\x1a\x10.pb.BaseResponseB\rZ\v/message_pbb\x06proto3"

var (
	file_PB_message_proto_rawDescOnce sync.Once
	file_PB_message_proto_rawDescData []byte
)

func file_PB_message_proto_rawDescGZIP() []byte {
	file_PB_message_proto_rawDescOnce.Do(func() {
		file_PB_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_message_proto_rawDesc), len(file_PB_message_proto_rawDesc)))
	})
	return file_PB_message_proto_rawDescData
}

var file_PB_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_PB_message_proto_goTypes = []any{
	(*Notification)(nil),              // 0: pb.Notification
	(*ListNotificationsRequest)(nil),  // 1: pb.ListNotificationsRequest
	(*ListNotificationsResponse)(nil), // 2: pb.ListNotificationsResponse
	(*UnreadCountRequest)(nil),        // 3: pb.UnreadCountRequest
	(*UnreadCountResponse)(nil),       // 4: pb.UnreadCountResponse
	(*MarkReadRequest)(nil),           // 5: pb.MarkReadRequest
	(*MarkAllReadRequest)(nil),        // 6: pb.MarkAllReadRequest
	(*DeleteNotificationRequest)(nil), // 7: pb.DeleteNotificationRequest
	(*common_pb.BaseResponse)(nil),    // 8: pb.BaseResponse
}
var file_PB_message_proto_depIdxs = []int32{
	0, // 0: pb.ListNotificationsResponse.notifications:type_name -> pb.Notification
	1, // 1: pb.MessageService.ListNotifications:input_type -> pb.ListNotificationsRequest
	3, // 2: pb.MessageService.UnreadCount:input_type -> pb.UnreadCountRequest
	5, // 3: pb.MessageService.MarkRead:input_type -> pb.MarkReadRequest
	6, // 4: pb.MessageService.MarkAllRead:input_type -> pb.MarkAllReadRequest
	7, // 5: pb.MessageService.DeleteNotification:input_type -> pb.DeleteNotificationRequest
	2, // 6: pb.MessageService.ListNotifications:output_type -> pb.ListNotificationsResponse
	4, // 7: pb.MessageService.UnreadCount:output_type -> pb.UnreadCountResponse
	8, // 8: pb.MessageService.MarkRead:output_type -> pb.BaseResponse
	8, // 9: pb.MessageService.MarkAllRead:output_type -> pb.BaseResponse
	8, // 10: pb.MessageService.DeleteNotification:output_type -> pb.BaseResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PB_message_proto_init() }
func file_PB_message_proto_init() {
	if File_PB_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_message_proto_rawDesc), len(file_PB_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PB_message_proto_goTypes,
		DependencyIndexes: file_PB_message_proto_depIdxs,
		MessageInfos:      file_PB_message_proto_msgTypes,
	}.Build()
	File_PB_message_proto = out.File
	file_PB_message_proto_goTypes = nil
	file_PB_message_proto_depIdxs = nil
}
